apiVersion: v1
kind: Pod
metadata:
  name: ambassador-example
  labels:
    name: ambassador-example

spec:
  containers:
    - name: nginx
    image: nginx
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"

    - name: twemproxy
    image: ganomede/twemproxy
    ports:
      - containerPort: 6379
        hostPort: 6379
    resources:
        limits:
          memory: "64Mi"
          cpu: "500m"
    command:
    - "nutcracker"
    - "-c"
    - "etc/config/nutcracker.yaml"
    - "-v"
    - "7"
    - "-s"
    - "6222"
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: twem-config

